name: Playwright Tests CI/CD

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 2 * * *' # Runs daily at 2am UTC

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run All Playwright Tests (Daily Schedule)
        if: github.event_name == 'schedule'
        run: npx playwright test

      - name: Run Smoke Tests (Push Event)
        if: github.event_name == 'push'
        run: npx playwright test --grep "@smoke"

      - name: Compress HTML Report
        run: |
          zip -r reports/playwright-report.zip reports/playwright-report
        if: always()

      - name: Upload HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: playwright-html-report
          path: reports/playwright-report.zip

      #- name: Upload test results
      #  if: failure()
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: playwright-results
      #    path: reports/playwright-report/
          
      #- name: Generate HTML Report
      #  run: |
      #    npx playwright show-report --output=playwright-report
      #    zip -r playwright-report.zip playwright-report

      #- name: Upload HTML Report
      #  uses: actions/upload-artifact@v3
      #  with:
      #   name: playwright-html-report
      #    path: playwright-report.zip